version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  commit-message:
    prefix: "deps"
    prefix-development: "deps(dev)"
  groups:
    chai:
      patterns:
        - "*chai*"
    eslint:
      patterns:
        - "*eslint*"
        - "*standard*"
    markdown:
      patterns:
        - "*mdast*"
        - "*micromark*"
    semantic-release:
      patterns:
        - "*semantic-release*"
    typedoc:
      patterns:
        - "*typedoc*"
