name: 'Cache node modules'
description: 'Cache node modules and dist files'
inputs:
  directories:
    description: 'Directories to cache'
    required: false
  build:
    description: 'Extra commands to run if nothing is cached'
    required: false
    default: 'echo'
  build_on_cache_fail:
    description: 'Whether you want to run `npm run --if-present build` if there is no cache
    require: false
    default: 'true' # defaulting to true to not break any existing users.
  cache_name:
    description: 'Cache name'
    required: false
    default: 'cache-node-modules'
runs:
  using: composite
  steps:
    # Windows I/O is so slow it's faster to just install the deps every time
    - if: ${{ runner.os != 'Windows' }}
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.npm
          ~/.cache
          ./dist
          ./types
          ./node_modules
          ./packages/*/dist
          ./packages/*/types
          ./packages/*/node_modules
          ${{ inputs.directories }}
        key: ${{ runner.os }}-build-${{ inputs.cache_name }}-${{ github.sha }}
    - if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
    - if: steps.cache.outputs.cache-hit != 'true' && ${{ inputs.build_on_cache_fail }} == 'true'
      run: npm run --if-present build
      shell: bash
    - if: steps.cache.outputs.cache-hit != 'true' && ${{ inputs.build }} != 'echo'
      run: ${{ inputs.build }}
      shell: bash
