name: 'Cache node modules'
description: 'Cache node modules and dist files'
inputs:
  directories:
    description: 'Directories to cache'
    required: false
  build:
    description: 'Extra commands to run if nothing is cached'
    required: false
  cache_name:
    description: 'Cache name'
    required: false
    default: 'cache-node-modules'
runs:
  using: composite
  steps:
    - uses: actions/cache@v2
      id: cache
      # Windows I/O is so slow it's faster to just install the deps every time
      if: ${{ runner.os }} != 'Windows'
      with:
        path: |
          ~/.npm
          ./dist
          ./node_modules
          ./packages/*/dist
          ./packages/*/node_modules
          ${{ inputs.directories }}
        key: ${{ runner.os }}-build-${{ inputs.cache_name }}-${{ github.sha }}
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
          npm install
          npm run --if-present build
          ${{ inputs.build }}
      shell: bash
